/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MediaRouteImport } from './routes/media'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamSlugRouteImport } from './routes/team/$slug'
import { Route as ResearchSlugRouteImport } from './routes/research/$slug'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResearchRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/positions': typeof PositionsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/positions': typeof PositionsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/positions': typeof PositionsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/media'
    | '/news'
    | '/positions'
    | '/publications'
    | '/research'
    | '/team'
    | '/news/$slug'
    | '/research/$slug'
    | '/team/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/media'
    | '/news'
    | '/positions'
    | '/publications'
    | '/research'
    | '/team'
    | '/news/$slug'
    | '/research/$slug'
    | '/team/$slug'
  id:
    | '__root__'
    | '/'
    | '/media'
    | '/news'
    | '/positions'
    | '/publications'
    | '/research'
    | '/team'
    | '/news/$slug'
    | '/research/$slug'
    | '/team/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRouteWithChildren
  PositionsRoute: typeof PositionsRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ResearchRouteChildren {
  ResearchSlugRoute: typeof ResearchSlugRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSlugRoute: ResearchSlugRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRouteWithChildren,
  PositionsRoute: PositionsRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
